config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :calendars
  root :to => "calendars#index"
  post '/' => "calendars#index"

  resources :calendars do
    resources :events, only: [:index, :create, :destroy, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
    belongs_to :user
    has_many :events
    validates :title, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :calendar
  validates :title, presence: true
  validates :start, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :calendars
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  helper_method :sort_column, :sort_direction

  before_action :require_login

    def index
      @calendars = FindCalendars.new(Calendar.all).call(permitted_params).order(sort_column + " " + sort_direction).page(params[:page]).per(30)
    end
    
    def show
      @calendar = Calendar.find(params[:id])
    end
    
    def new
      @calendar = current_user.calendars.new
      respond_to do |format|
        format.js
      end
    end

    def create
      @calendar = current_user.calendars.create(calendar_params)
      if @calendar.save
        redirect_to root_path
      else
        render :new
      end
    end

    def edit
      @calendar = Calendar.find(params[:id])
      respond_to do |format|
        format.js
      end
    end

    def update
      @calendar = Calendar.find(params[:id])
        if @calendar.update(calendar_params)
        redirect_to root_path
      else
        render 'edit'
      end
    end

    def destroy
      @calendar = Calendar.find(params[:id])
      @calendar.destroy
      redirect_to root_path
    end

    private

    def require_login
      unless user_signed_in?
        flash[:error] = "You are not authorized!"
        redirect_to new_user_session_path
      end
    end

    def calendar_params
      params.require(:calendar).permit(:title, :public)
    end

    def permitted_params
      params.permit(:calendar_name, :created_at, :public, :direction, :sort, :utf8, :authenticity_token)
    end
  
    def sort_column
      params[:sort] ? params[:sort] : "created_at" 
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
  def index
    render json: Event.where(calendar_id: params[:calendar_id])
  end

  def create
    event = Event.create!(event_params)
    render json: event
  end

  def destroy
    Event.destroy(params[:id])
  end

  def update
    event = Event.find(params[:id])
    event.update_attributes(event_params)
    render json: event
  end

  private

  def event_params
    params.require(:event).permit(:id, :title, :allDay, :start, :end, :url, :calendar_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.create(users_params)
    @user = login(users_params[:email], users_params[:password], users_params[:remember])
    redirect_to root_path
  end

  def update
    @user = User.find(params[:id])
    if @user.update(users_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def users_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction, :public => params[:public], :calendar_name => params[:calendar_name], :created_at => params[:created_at] }, {:class => css_class}
  end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendars/_form.html.erb
<div id="calendar-modal" class="modal fade modal-class">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <% if controller.action_name == "new" %>
          <h3 id="myModalLabel">Add calendar</h3>
        <% else%>
          <h3 id="myModalLabel">Edit calendar</h3>
         <% end %>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
      </div>

      <%= form_for @calendar, remote: true do |f| %>
      <div class="modal-body">
        <div class="container">
          <div class="row align-top">

            <div class="col-2 align-self-center">
              <%= f.label :title, "Title:", class: "control-label" %>
            </div>

            <div class="col-10">
              <%= f.text_field :title, placeholder: "Title", autofocus: true, class: "form-control" %>
            </div>
            
          </div>

          <div class="row align-bottom">
            <div class="col-2 align-self-center">
              Public?
            </div>

            <div class="col-10">
              <%= f.check_box :public, class: "checkbox" %>
            </div>

          
          </div>
        </div>
      </div>

      <div class="modal-footer">

        <% if controller.action_name == "new" %>
          <%= f.submit "Create", :class => 'btn btn-success' %>
        <% else%>
          <%= f.submit "Update", :class => 'btn btn-success' %>
        <% end %>

        <button class="btn btn-secondary" data-dismiss="modal" aria-hidden="true">Cancel</button>
      </div>
    <% end %>
    
    </div>
  </div>
</div>

app/views/calendars/edit.html.erb
<%="Here should be edit form for calendar"%>

app/views/calendars/edit.js.erb
$(".modal-class").html('<%= j render "form" %>')
$("#calendar-modal").modal('show');

app/views/calendars/index.html.erb
<% if current_user %>

<h1>Dashboard</h1>

  <div class="row">
  <%= form_tag('/', { :controller => 'calendars', :action => 'index'}) do %>

  <% if params[:direction] %>
    <% hidden_field_tag 'direction', params[:direction] %>
  <% end %>

  <% if params[:sort] %>
    <% hidden_field_tag 'sort', params[:sort] %>
  <% end %>

    <div class="container">
      <div class="form-group row">

        <div class="col-6 align-self-center">
          <%= text_field_tag(:calendar_name, (params[:calendar_name].present? ? params[:calendar_name] : nil), {class: "form-control", placeholder: 'Enter search name...'}) %>
        </div>

      <div class="col-2 align-self-center">
        <%= "Status" %>
      </div>
    
      <div class="col-2 align-self-center">
        <%= select_tag "public", options_for_select(["All", "Private", "Public"], (params[:public].present? ? params[:public] : "All")) %>
      </div>

        <div class="col-2">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>

      </div>
    </div>

  <% end %>
</div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col"><%= sortable "title", "Calendar Name" %></th>
        <th scope="col"><%= sortable "public", "Status" %></th>
        <th scope="col">Shortened Link</th>
        <th scope="col"><%= sortable "created_at", "Date/Time" %></th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @calendars.each do |calendar| %>
        <tr>
          <td><%= link_to(calendar.title, calendar)  %></td>
          <td><%= calendar.public ? "Public" : "Private" %></td>
          <td><%= calendar.public ? "Shortened Link should be here" : "" %></td>
          <td><%= calendar.created_at.strftime("%d:%m:%Y %I:%M") %></td>
          <td>
            <%= link_to 'Edit', edit_calendar_path(calendar), remote: true, :class => "btn btn-secondary"  %>
            <%= link_to('Delete', calendar_path(calendar), method: :delete, data: { confirm: 'Are you sure?'}, :class => "btn btn-warning") %>
          
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "Create New", new_calendar_path, remote: true, class: "btn btn-primary" %>
<% end %>

<%= paginate @calendars, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm  justify-content-center" %>

app/views/calendars/new.js.erb
$(".modal-class").html('<%= j render "form" %>')
$("#calendar-modal").modal('show');

app/views/calendars/show.html.erb
<%= react_component("Main", {calendar_id: params[:id]}) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scheduler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <%= render "shared/navbar" %>
  <div class="container">
    <%= yield %>
  </div>

  <div class="modal-class"></div>
  

  
  </body>

</html>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-ligth bg-primary">
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "btn btn-primary" %>
  </nav>
<% else %>
<nav class="navbar navbar-ligth bg-primary">
  <form class="form-inline">
      <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-primary" %>
      <%= link_to "Login", new_user_session_path, :class => "btn btn-primary" %>
  </form>
</nav>
<% end %>

app/views/users/_form.html.erb
<%= "here will be form"%>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render 'form' %>